### Default mandlebrot
GET http://127.0.0.1:7071/api/createFractal?zoom=4&r=-1.5
### Default Julia
GET http://127.0.0.1:7071/api/createFractal?type=julia

### Lightning looking 
GET http://127.0.0.1:7071/api/createFractal?r=-0.1599&i=-1.0185&zoom=388&bright=290&hue=200&w=400&h=300

### Test mandlebrot
GET http://127.0.0.1:7071/api/createFractal?zoom=10&i=-1&r=-0.131&hue=220

### Frosty!
http://127.0.0.1:7071/api/createFractal?i=0.32840108139174217&r=0.4540288116894214&zoom=190&hue=190&bright=120

###########################################################

### Make a random fractal
GET http://127.0.0.1:7071/api/randomFractal

###########################################################

### Generate points data
GET http://127.0.0.1:7071/api/createPoints?iters=60&w=400&h=300